name: Cache Go Dependencies
description: Cache Go Dependencies
inputs:
  save:
    description: 'Whether this job is eligible to save caches. Actual saving only happens on pushes to save-on-ref.'
    required: false
    default: 'true'
  save-on-ref:
    description: 'Git ref that triggers cache saving on push events.'
    required: false
    default: refs/heads/master
  cache-group:
    description: 'GOCACHE group name. Jobs with the same group share a cache. Defaults to github.job for per-job isolation.'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Determine Go cache paths
      id: cache-paths
      run: |
        echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
        echo "GOMODCACHE=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
        echo "GOARCH=$(go env GOARCH)" >> "$GITHUB_OUTPUT"
        group="${{ inputs.cache-group }}"
        echo "group=${group:-${{ github.job }}}" >> "$GITHUB_OUTPUT"
        # TODO(davdhacs): remove force-save after validating warm cache on PR
        echo "save=${{ inputs.save == 'true' && (github.event_name == 'push' && github.ref == inputs.save-on-ref || github.event_name == 'pull_request') }}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache Go Dependencies
      if: steps.cache-paths.outputs.save == 'true'
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.cache-paths.outputs.GOMODCACHE }}
        key: go-mod-v1-${{ hashFiles('**/go.sum') }}
        restore-keys: go-mod-v1-

    - name: Restore Go Dependencies
      if: steps.cache-paths.outputs.save != 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ steps.cache-paths.outputs.GOMODCACHE }}
        key: go-mod-v1-${{ hashFiles('**/go.sum') }}
        restore-keys: go-mod-v1-

    - name: Cache Go Build
      if: steps.cache-paths.outputs.save == 'true'
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.cache-paths.outputs.GOCACHE }}
        key: go-build-v1-${{ steps.cache-paths.outputs.group }}-${{ steps.cache-paths.outputs.GOARCH }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-build-v1-${{ steps.cache-paths.outputs.group }}-${{ steps.cache-paths.outputs.GOARCH }}-

    - name: Restore Go Build
      if: steps.cache-paths.outputs.save != 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ steps.cache-paths.outputs.GOCACHE }}
        key: go-build-v1-${{ steps.cache-paths.outputs.group }}-${{ steps.cache-paths.outputs.GOARCH }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-build-v1-${{ steps.cache-paths.outputs.group }}-${{ steps.cache-paths.outputs.GOARCH }}-

    - name: Report cache restore timing
      run: |
        echo "::notice::Cache restore completed (GOCACHE group=${{ steps.cache-paths.outputs.group }} arch=${{ steps.cache-paths.outputs.GOARCH }} save=${{ steps.cache-paths.outputs.save }})"
      shell: bash

    - name: Download Go modules
      run: make deps --always-make
      shell: bash
