name: Cache Go Dependencies
description: Cache Go Dependencies
runs:
  using: composite
  steps:
    - name: Determine Go cache paths
      id: cache-paths
      run: |
        echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
        echo "GOMODCACHE=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
        echo "GOARCH=$(go env GOARCH)" >> "$GITHUB_OUTPUT"
        echo "TAG=$(make --quiet --no-print-directory tag)" >> "$GITHUB_OUTPUT"
      shell: bash

    # Save caches only on pushes to the default branch.
    # All other events (PRs, etc.) restore only.
    # TODO(davdhacs): remove 'true ||' after validating warm cache on PR
    - name: Cache Go Dependencies
      if: true || github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.cache-paths.outputs.GOMODCACHE }}
        key: go-mod-v1-${{ hashFiles('**/go.sum') }}
        restore-keys: go-mod-v1-

    - name: Cache Go Dependencies
      if: ${{ !(true || github.event_name == 'push' && github.ref_name == github.event.repository.default_branch) }}
      uses: actions/cache/restore@v5
      with:
        path: ${{ steps.cache-paths.outputs.GOMODCACHE }}
        key: go-mod-v1-${{ hashFiles('**/go.sum') }}
        restore-keys: go-mod-v1-

    # TODO(davdhacs): remove 'true ||' after validating warm cache on PR
    - name: Cache Go Build
      if: true || github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.cache-paths.outputs.GOCACHE }}
        key: go-build-v1-${{ github.job }}-${{ steps.cache-paths.outputs.GOARCH }}-${{ steps.cache-paths.outputs.TAG }}
        restore-keys: go-build-v1-${{ github.job }}-${{ steps.cache-paths.outputs.GOARCH }}-

    - name: Cache Go Build
      if: ${{ !(true || github.event_name == 'push' && github.ref_name == github.event.repository.default_branch) }}
      uses: actions/cache/restore@v5
      with:
        path: ${{ steps.cache-paths.outputs.GOCACHE }}
        key: go-build-v1-${{ github.job }}-${{ steps.cache-paths.outputs.GOARCH }}-${{ steps.cache-paths.outputs.TAG }}
        restore-keys: go-build-v1-${{ github.job }}-${{ steps.cache-paths.outputs.GOARCH }}-

    - name: Download Go modules
      run: make deps --always-make
      shell: bash
